
/*
	Copyright 2023 Efabless Corporation

	Author: Ahmed Reda (ahmed.reda@efabless.com)

	This file is auto-generated by wrapper_gen.py

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#define DAC_BASE				0x00000000

#define	DAC_DATA_REG_ADDR		(DAC_BASE+0x0)
#define	DAC_CTRL_REG_ADDR		(DAC_BASE+0x4)
#define	DAC_FIFOT_REG_ADDR		(DAC_BASE+0x8)
#define	DAC_SAMPCTRL_REG_ADDR		(DAC_BASE+0xc)
#define	DAC_ICR_REG_ADDR		(DAC_BASE+0xf00)
#define	DAC_RIS_REG_ADDR		(DAC_BASE+0xf04)
#define	DAC_IM_REG_ADDR		(DAC_BASE+0xf08)
#define	DAC_MIS_REG_ADDR		(DAC_BASE+0xf0c)

#define DAC_DATA_REG_DATA		0
#define DAC_DATA_REG_DATA_LEN	10
#define DAC_CTRL_REG_EN		0
#define DAC_CTRL_REG_EN_LEN	1
#define DAC_FIFOT_REG_FIFO_THRESHOLD		0
#define DAC_FIFOT_REG_FIFO_THRESHOLD_LEN	5
#define DAC_SAMPCTRL_REG_CLK_EN		0
#define DAC_SAMPCTRL_REG_CLK_EN_LEN	1
#define DAC_SAMPCTRL_REG_CLKDIV		8
#define DAC_SAMPCTRL_REG_CLKDIV_LEN	20
#define INT_FIFO_EMPTY_FLAG	0x1
#define INT_FIFO_LOW_FLAG	0x2

volatile unsigned int * dac_DATA	= (volatile unsigned int *) DAC_DATA_REG_ADDR;
volatile unsigned int * dac_CTRL	= (volatile unsigned int *) DAC_CTRL_REG_ADDR;
volatile unsigned int * dac_FIFOT	= (volatile unsigned int *) DAC_FIFOT_REG_ADDR;
volatile unsigned int * dac_SAMPCTRL	= (volatile unsigned int *) DAC_SAMPCTRL_REG_ADDR;
