
/*
	Copyright 2023 Efabless Corporation

	Author: Ahmed Reda (ahmed.reda@efabless.com)

	This file is auto-generated by wrapper_gen.py on 2023-11-28

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#ifndef IO_TYPES
#define IO_TYPES
#define   __R     volatile const unsigned int
#define   __W     volatile       unsigned int
#define   __RW    volatile       unsigned int
#endif

#define EF_DAC1001_DI_DATA_REG_DATA		0
#define EF_DAC1001_DI_DATA_REG_DATA_LEN	10
#define EF_DAC1001_DI_CTRL_REG_EN		0
#define EF_DAC1001_DI_CTRL_REG_EN_LEN	1
#define EF_DAC1001_DI_FIFOT_REG_FIFO_THRESHOLD		0
#define EF_DAC1001_DI_FIFOT_REG_FIFO_THRESHOLD_LEN	5
#define EF_DAC1001_DI_SAMPCTRL_REG_CLK_EN		0
#define EF_DAC1001_DI_SAMPCTRL_REG_CLK_EN_LEN	1
#define EF_DAC1001_DI_SAMPCTRL_REG_CLKDIV		8
#define EF_DAC1001_DI_SAMPCTRL_REG_CLKDIV_LEN	20
#define EF_DAC1001_DI_FIFO_EMPTY_FLAG	0x1
#define EF_DAC1001_DI_FIFO_LOW_FLAG	0x2

typedef struct _EF_DAC1001_DI_TYPE_ {
	__RW	DATA;
	__RW	CTRL;
	__RW	FIFOT;
	__RW	SAMPCTRL;
	__R 	reserved[956];
	__W 	icr;
	__R 	ris;
	__RW	im;
	__R 	mis;
} EF_DAC1001_DI_TYPE;
